# Generated by Django 5.0 on 2024-01-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstor', '0005_product_img1_product_img2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img3',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
