# Generated by Django 5.0 on 2024-01-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstor', '0007_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
