# Generated by Django 5.0 on 2024-01-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstor', '0009_remove_address_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='caty',
            new_name='city',
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
